# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26cf029e539f36e07ebea596e3ca2f4a8c2ff09102b60927cc6d4c40754f7fc158bc4cfd19057006d7635f53962e57ae55e04ae319f742843a08c0e9df12026c

test:
  secret_key_base: 2b7e5d67fed623416f146cb93d2b60675459a12bf5250d837d8b389787f9cf052a199c569b7f9c57b6192ed3a1815dbb9d278581dddc06a6e7aa9bc83d71163d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
